### ISSUE TITLE
I have no idea what to do with this!

### ISSUE THREAD

**Issue by Cassolotl** [instajelly/mastodon-skins#1]
I'm not very technologically-inclined but I would really like to try this. Can there be some kind of guide for absolute noobs on how to install this?

Thanks!

**Comment by instajelly** [comment]
You need to install Stylish for your browser (Chrome, Firefox, etc). I know Edge doesn't have anything like this.

If you installed the plugin, click on the icon and click "Create new style".

For Chrome: under the big textarea (where you should put the CSS code), there is a select "Applied to". Choose "URL starting with" and put there your Mastodon domain `https://mastodon.social/` for me.

For Firefox: before the CSS code, in the textarea paste this: 

    @-moz-document url-prefix("mastodon.social"), url-prefix("https://mastodon.social/") {

and then add extra `}` at the end.

**Comment by Cassolotl** [comment]
Thanks! Could this maybe go on the main page under the code thing?

**Comment by instajelly** [comment]
Yes, I just updated the readme file!

**Comment by Cassolotl** [comment]
Oh great! :)

The text has disappeared - I'm not used to this, but I can probably find it...

**Comment by instajelly** [comment]
What text?

**Comment by Cassolotl** [comment]
The CSS text! I found it though, I clicked "accessibility.css" at the top. :)

**Comment by instajelly** [comment]
Oh, great ;)

**Comment by Cassolotl** [comment]
Thanks for everything, @instajelly!
